#!/bin/bash

set -eoux pipefail

cat << \EOF >/etc/motd
    #############  GETTING STARTED #############
    Welcome to the Getting Started EDURange scenario!
    You can use this bash environment to try out the commands shown in the student guide.
    Follow the student guide and answer the questions on EDURange in browser.
    ############################################
EOF

echo 'cat /etc/motd' >> /etc/bash.bashrc
