#!/bin/bash
set -euxo pipefail

player=$1
super_secret=$2
follow_me_filename=$3

studentDIR=/home/$player

# imageLoc is an array used to disperse images to multiple locations that I set up later
imageLoc=($studentDIR/i/b/e/j/l/s/v/ $studentDIR/i/a/g/kitty/m/q/w/ $studentDIR/i/c/e/h/k/ $studentDIR/i/a/e/kitty/ $studentDIR/i/z/g/j/l/o/w/ $studentDIR/i/d/f/kitty/k/n/t/)
imageName=(002edurange.jpg edurange001.gif edurange3.GIF 4edurange.jpeg edurange006weeeeeee.png edurange5meow.JPG)

# Making directories and chmoding them for the scenario
mkdir -p $studentDIR/followMe/keepGOING/another\ folder\ wee/im.another.folder/WOOT/dontstop/okYouAreHERE\!
touch $studentDIR/followMe/keepGOING/another\ folder\ wee/im.another.folder/WOOT/dontstop/okYouAreHERE\!/$follow_me_filename
mkdir $studentDIR/stuff
chown -R $player:$player $studentDIR/followMe
chmod -R 440 /$studentDIR/followMe
chown -R $player:$player $studentDIR/stuff
chmod -R 440 /$studentDIR/stuff

mkdir $studentDIR/toLearn
cp /home/ubuntu/toLearn/* $studentDIR/toLearn/
chown -R $player:$player $studentDIR/toLearn
chmod -R 440 $studentDIR/toLearn

cp /home/ubuntu/stuff/* $studentDIR/stuff/

echo "SECRET CODE: $super_secret" > $studentDIR/stuff/imatextfiletoo.txt

# More setting up for the scenario
mkdir $studentDIR/textfiles
echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sed ullamcorper nisi. Morbi risus libero, ultricies in condimentum in, porttitor sit amet quam. Curabitur ultrices, magna ut viverra posuere, urna massa molestie ex, at pellentesque magna justo eget arcu. Vestibulum eget ante vulputate, euismod lacus in, lobortis nisl. Suspendisse tempus maximus erat ut consectetur. Donec molestie massa vitae commodo ultricies. Integer dignissim leo consequat nisi sodales, acvolutpat magna
euismod. Maecenas urna sem, congue et libero nec, viverra condimentum ante. Praesent bibendum nulla ut sapien volutpat tincidunt. Sed sed nibh id ante maximus dignissim. Sed congue egestas lacinia. Duis non finibus arcu, a viverra mauris. Nunc ac felis ac turpis congue faucibus." > /$studentDIR/textfiles/one.txt
echo "7625837645734265487236549367527365827634587623485763982576489237645832765489762385497632" > /$studentDIR/textfiles/two.txt
echo -e "Fighting evil by moonlight\nWinning love by daylight\nNever running from a real fight\nShe is the one named Sailor Moon\nShe will never turn her back on a friend\nShe is always there to defend\nShe is the one on whom we depend" > $studentDIR/textfiles/three.txt
chown -R $player:$player $studentDIR/textfiles
chmod -R 660 $studentDIR/textfiles
mkdir $studentDIR/editme
echo -e "Line 1\nLine 2\nLine 3\nLine 4\nLine 5" > $studentDIR/editme/editme.txt
chown -R $player:$player $studentDIR/editme
chmod -R 660 $studentDIR/editme

# This is a nifty way to create multiple folders all at once :3
mkdir -p /$studentDIR/i/{a,b,c,d,z,y,x}/{e,f,g}/{h,kitty,j}/{k,l,m}/{n,o,p,q,r,s}/{t,u,v,w}

# Counter is used for the following for loop. Taking each image in the folder images and moving them to a new location
counter=0
for filename in /home/ubuntu/images/*;
do
    cp $filename ${imageLoc[$counter]}${imageName[$counter]}
    counter=$((counter+1))
done

chown -R $player:$player $studentDIR/i
chmod -R 440 $studentDIR/i

# Final Mission setup
#cp /home/ubuntu/final-mission/U348bdks8cowFJS8dJF3hHDFj.jpg $studentDIR/i/y/f/kitty/k/r/u/U348bdks8cowFJS8dJF3hHDFj.jpg
#cp /home/ubuntu/final-mission/.donthackme $studentDIR/i/y/f/kitty/k/r/u/.donthackme
#chmod -R 660 $studentDIR/i/y/f/kitty/k/r/u/*
mkdir $studentDIR/final-mission
chown -R $player:$player $studentDIR/final-mission
chmod 660 $studentDIR/final-mission
find $studentDIR -type d -print0 | xargs -0 chmod +x
