#!/bin/bash
set -eoux pipefail

mkdir /usr/local/src/logs
mkdir /usr/local/src/ttylog

chmod 755 /usr/local/src
chmod 777 /usr/local/src/logs
chmod 777 /usr/local/src/ttylog

mv /home/ubuntu/ttylog/analyze.py /usr/local/src/ttylog/
mv /home/ubuntu/ttylog/start_ttylog.sh /usr/local/src/ttylog/
mv /home/ubuntu/ttylog/ttylog /usr/local/src/ttylog/
mv /home/ubuntu/ttylog/analyze_cyclic.pl /usr/local/src/ttylog/
mv /home/ubuntu/ttylog/makeTsv.py /usr/local/src/ttylog/makeTsv.py

chmod +x /usr/local/src/ttylog/start_ttylog.sh
chmod +x /usr/local/src/ttylog/ttylog
chmod +x /usr/local/src/ttylog/analyze_cyclic.pl
chmod +x /usr/local/src/ttylog/analyze.py
chmod +x /usr/local/src/ttylog/makeTsv.py

awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd > /usr/local/src/user_names.txt

while read line; do
	mkdir /usr/local/src/logs/$line
	touch /usr/local/src/logs/$line/.cli.csv
	chmod 777 /usr/local/src/logs/$line
	chmod 777 /usr/local/src/logs/$line/.cli.csv
	echo "$line ALL=(ALL) NOPASSWD: /bin/mkdir -p /usr/local/src/logs/" | sudo EDITOR='tee -a' visudo
	echo "$line ALL=(ALL) NOPASSWD: /bin/touch /usr/local/src/logs/count.$(hostname)" | sudo EDITOR='tee -a' visudo
	echo "$line ALL=(ALL) NOPASSWD: /bin/chmod ugo+rw /usr/local/src/logs/count.$(hostname)" | sudo EDITOR='tee -a' visudo
	#echo "$line ALL=(ALL) NOPASSWD: /usr/local/src/ttylog/ttylog .*" | sudo EDITOR='tee -a' visudo
	echo "$line ALL=(ALL) NOPASSWD: /usr/local/src/ttylog/ttylog *" | sudo EDITOR='tee -a' visudo
	echo "$line ALL=(ALL) NOPASSWD: /usr/bin/tee -a /usr/local/src/logs/ttylog.*.*.*" | sudo EDITOR='tee -a' visudo
	echo "$line ALL=(ALL) NOPASSWD: /bin/touch /usr/local/src/logs/ttylog.$(hostname).*.*" | sudo EDITOR='tee -a' visudo
	echo "$line ALL=(ALL) NOPASSWD: /bin/chmod ugo+rw /usr/local/src/logs/ttylog.$(hostname).*.*" | sudo EDITOR='tee -a' visudo
	echo "$line ALL=(ALL) NOPASSWD: /usr/bin/perl /usr/local/src/analyze_cyclic.pl &" | sudo EDITOR='tee -a' visudo
	echo "$line ALL=(ALL) NOPASSWD: /usr/bin/python3.4 /usr/local/src/analyze.py /usr/local/src/logs/alltty.$(hostname)* /usr/local/src/logs/cli.$(hostname)*" | sudo EDITOR='tee -a' visudo
done</usr/local/src/user_names.txt


if grep -q "ForceCommand /usr/local/src/ttylog/start_ttylog.sh" /etc/ssh/sshd_config; then
	:
else
	echo "ForceCommand /usr/local/src/ttylog/start_ttylog.sh" >> /etc/ssh/sshd_config
fi

systemctl restart sshd

echo 'if [[ -n $SSH_CONNECTION ]] ; then' >> /etc/bash.bashrc
echo "	perl /usr/local/src/ttylog/analyze_cyclic.pl &" >> /etc/bash.bashrc
echo "  cat /etc/motd" >> /etc/bash.bashrc
echo "fi" >> /etc/bash.bashrc



