#!/bin/bash -p

# Copy all user files to user directories
echo "Copying user files"
shopt -s dotglob # List dot files (files beginning with .) in expansion

# [lyn, 10/09/2012] Below is the code from 2010, but I don't see how this 
# could have worked in 2010 without the untarring from ./install. 
# How would it get permissions right on all the subdirectories?
# Don't we need to do tarring/untarring to do this? 
# Well, do it now!
for USER in awan bduomo cdry dshi equintus fsexon ghepta hochoa inunez jdekka kelva ldouzette pkaideka pradessime qsanera tdaforth; do 
  echo "Removing $USER files";
  rm -rf /home/$USER/*
  echo "Copying $USER files";
  cp -R -p /home/ubuntu/users/$USER/* /home/$USER;
  chmod 755 /home/$USER;
  # [lyn, 9/27/2012] SELINUX not used on Ubuntu in Fall '12
  # restorecon -R -v /home/$USER; # SELinux magic for making public_html dirs accessible
done

# recompile bininaries
gcc /home/cdry/bin/archive.c -o /home/cdry/bin/archive
chown cdry /home/cdry/bin/archive
chmod  4775 /home/cdry/bin/archive

gcc /home/dshi/bin/backup.c -o /home/dshi/bin/backup
chown dshi /home/dshi/bin/backup
chmod  4775 /home/dshi/bin/backup

gcc /home/kelva/bin/swap.c -o /home/kelva/bin/swap
chown kelva /home/kelva/bin/swap
chmod  6775 /home/kelva/bin/swap

chmod  777 /home/pkaideka/private
gcc /home/pkaideka/private/guess_my_password.c -o /home/pkaideka/guess_my_password
chown pkaideka /home/pkaideka/guess_my_password
chmod  755 /home/pkaideka/guess_my_password
chmod  750 /home/pkaideka/private

cp /bin/cp /home/ghepta/bin/cp

# allow public_html home directories
cd /etc/apache2/conf.d
if ! [ -e userdir.conf ]
then ln -s ../conf.d/userdir.conf userdir.conf
fi
if ! [ -e userdir.load ]
then ln -s ../conf.d/userdir.load userdir.load
fi


# Restart apache to deal with new groups and such
exec /usr/sbin/httpd -D FOREGROUND -f /etc/apache2/httpd.conf &>/dev/null &

for USER in awan bduomo cdry dshi equintus fsexon ghepta hochoa inunez jdekka kelva ldouzette pkaideka pradessime qsanera tdaforth; do
  chown root /home/$USER/.bash_history
  chmod 640 /home/$USER/.bash_history
done

chmod 644 /home/jdekka/.bash_history
