#!/bin/bash

awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd > /usr/local/src/user_names.txt
sudo mv /cgconfig.conf /etc/cgconfig.conf
sudo touch /etc/cgrules.conf

while read line; do
  echo "$line  memory  memlimit/" | tee -a /etc/cgrules.conf
done</usr/local/src/user_names.txt
