#!/bin/bash
set -eoux pipefail

mkdir -p /usr/local/src/logs
mkdir -p /usr/local/src/ttylog
mkdir -p /usr/local/src/logs/root
mkdir -p /var/log/annotator

touch /usr/local/src/logs/root/.cli.csv

chmod 755 /usr/local/src
chmod 777 /usr/local/src/logs
chmod 777 /usr/local/src/ttylog
chmod 777 /var/log/annotator/

mv /home/ubuntu/analyze.py /usr/local/src/ttylog/
mv /home/ubuntu/start_ttylog.sh /usr/local/src/ttylog/
mv /home/ubuntu/ttylog /usr/local/src/ttylog/
mv /home/ubuntu/makeTsv.py /usr/local/src/ttylog/makeTsv.py
mv /home/ubuntu/milestone-lbl.pl /usr/local/src/ttylog/milestone-lbl.pl
mv /home/ubuntu/intervention.py /usr/local/src/ttylog/intervention.py

chmod +x /usr/local/src/ttylog/start_ttylog.sh
chmod +x /usr/local/src/ttylog/ttylog
chmod +x /usr/local/src/ttylog/analyze.py
chmod +x /usr/local/src/ttylog/makeTsv.py
chmod +x /usr/local/src/ttylog/intervention.py
chmod +x /usr/local/src/ttylog/milestone-lbl.pl

awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd > /usr/local/src/user_names.txt

while read line; do
	mkdir -p /usr/local/src/logs/$line
	touch /usr/local/src/logs/$line/.cli.csv
	chmod 777 /usr/local/src/logs/$line
	chmod 777 /usr/local/src/logs/$line/.cli.csv
	echo "$line ALL=(ALL) NOPASSWD: /bin/mkdir -p /usr/local/src/logs/" | sudo EDITOR='tee -a' visudo
	echo "$line ALL=(ALL) NOPASSWD: /bin/mkdir -p /usr/local/src/logs/analyze_cont/" | sudo EDITOR='tee -a' visudo
	echo "$line ALL=(ALL) NOPASSWD: /bin/mkdir -p /var/log/annotator/" | sudo EDITOR='tee -a' visudo

	echo "$line ALL=(ALL) NOPASSWD: /bin/cat /usr/local/src/logs/count.*" | sudo EDITOR='tee -a' visudo

	echo "$line ALL=(ALL) NOPASSWD: /bin/touch /usr/local/src/logs/count.$(hostname)" | sudo EDITOR='tee -a' visudo
	echo "$line ALL=(ALL) NOPASSWD: /bin/touch /usr/local/src/logs/analyze_cont/analyze.$line.*.csv" | sudo EDITOR='tee -a' visudo
  echo "$line ALL=(ALL) NOPASSWD: /bin/touch /usr/local/src/logs/$line/ttylog.$line.*" | sudo EDITOR='tee -a' visudo
  echo "$line ALL=(ALL) NOPASSWD: /bin/touch /var/log/annotator/annotate.$line.*" | sudo EDITOR='tee -a' visudo

	echo "$line ALL=(ALL) NOPASSWD: /usr/local/src/ttylog/ttylog *" | sudo EDITOR='tee -a' visudo

  echo "$line ALL=(root) NOPASSWD: /bin/kill" | sudo EDITOR='tee -a' visudo

	echo "$line ALL=(ALL) NOPASSWD: /usr/bin/tee /usr/local/src/logs/count.*" | sudo EDITOR='tee -a' visudo

	echo "$line ALL=(ALL) NOPASSWD: /bin/chmod ugo+rw /usr/local/src/logs/count.$(hostname)" | sudo EDITOR='tee -a' visudo
	echo "$line ALL=(ALL) NOPASSWD: /bin/chmod ugo+rw /usr/local/src/logs/$line/ttylog.$line.*" | sudo EDITOR='tee -a' visudo

	echo "$line ALL=(ALL) NOPASSWD: /usr/bin/python3 /usr/local/src/ttylog/analyze.py /usr/local/src/logs/$line/ttylog.$line.* /usr/local/src/logs/analyze_cont/analyze.$line.*.csv" | sudo EDITOR='tee -a' visudo
  echo "$line ALL=(ALL) NOPASSWD: /usr/bin/perl /usr/local/src/ttylog/milestone-lbl.pl /var/log/milestones/milestone_file /usr/local/src/logs/analyze_cont/analyze.$line.*.csv /var/log/annotator/annotate.$line.*" | sudo EDITOR='tee -a' visudo
  echo "$line ALL=(ALL) NOPASSWD: /usr/bin/python3 /usr/local/src/ttylog/intervention.py /var/log/annotator/annotate.$line.* /var/log/milestones/milestone_file /var/log/milestones/milestone_messages" | sudo EDITOR='tee -a' visudo

done</usr/local/src/user_names.txt


if grep -q "ForceCommand /usr/local/src/ttylog/start_ttylog.sh" /etc/ssh/sshd_config; then
	:
else
	echo "ForceCommand /usr/local/src/ttylog/start_ttylog.sh" >> /etc/ssh/sshd_config
fi

echo "cat /var/log/annotator/* > /usr/local/src/mergeLogs.csv" > /usr/local/src/mergeLogs.sh
echo "zip /usr/local/src/raw_logs /usr/local/src/logs /var/log/annotator" > /usr/local/src/zipRawLogs.sh

service ssh reload
service cron start



