#!/bin/bash
set -euxo pipefail
login=$1
password=$2
for i in {1..100}; do
  mkdir /home/$login/dir$i
  echo $RANDOM | md5sum | cut -c -32 > /home/$login/dir$i/file.txt
  chown -R $login:$login /home/$login/dir$i/
done
echo "to login as $login at the ip address 10.0.0.16 use the password $password" > /home/$login/dir$(shuf -i 1-100 -n 1)/file.txt
