#!/usr/bin/env ruby

# generates 39 example players for the `terraform.tfvars.json` file

require 'unix_crypt'
require 'securerandom'
require 'json'

class Password

  def initialize plaintext
    @plaintext = plaintext
    @hash = UnixCrypt::SHA512.build(plaintext)
  end

  attr_reader :plaintext, :hash

  def self.random
    Password.new(SecureRandom.hex(5))
  end

  def to_json opts
    {
      plaintext: plaintext,
      hash: hash
    }.to_json(opts)
  end

end

class Player

  def initialize name
    @login = name
    @password = Password.random
    @fourth_stop_password = Password.random
    @fifth_stop_password = Password.random
    @satans_palace_password = Password.random
    @secret_starting_line = SecureRandom.hex(5)
    @secret_first_stop = SecureRandom.hex(5)
    @secret_second_stop = SecureRandom.hex(5)
    @secret_third_stop = SecureRandom.hex(5)
    @secret_fourth_stop = SecureRandom.hex(5)
    @secret_fifth_stop = SecureRandom.hex(5)
    @master_string = SecureRandom.hex(5)
  end

  def to_json(opts)
    {
      login: @login,
      password: @password,
      fourth_stop_password: @fourth_stop_password,
      fifth_stop_password: @fifth_stop_password,
      satans_palace_password: @satans_palace_password,
      secret_starting_line: @secret_starting_line,
      secret_first_stop: @secret_first_stop,
      secret_second_stop: @secret_second_stop,
      secret_third_stop: @secret_third_stop,
      secret_fourth_stop: @secret_fourth_stop,
      secret_fifth_stop: @secret_fifth_stop,
      master_string: @master_string
    }.to_json(opts)
  end

end

names = [
  'gilberto',
  'gary',
  'gertrude',
  'norman',
  'mark',
  'walter',
  'kristi',
  'hubert',
  'kenneth',
  'jerome',
  'moses',
  'margarita',
  'eula',
  'harry',
  'darla',
  'lydia',
  'scott',
  'wallace',
  'howard',
  'celia',
  'kristine',
  'fred',
  'ervin',
  'sophia',
  'danilo',
  'yohanes',
  'miroslava',
  'mikala',
  'romeu',
  'macy',
  'mariann',
  'ala',
  'borna',
  'melanthios',
  'sunita',
  'justin',
  'moe',
  'murrough',
  'adalberht'
]

players = names.map{|name| Player.new name}
vars = {
  players: players,
  scenario_id: SecureRandom.uuid
}
puts JSON.pretty_generate(vars)
