#!/bin/bash

set -eoux pipefail

cat << \EOF >/etc/motd
                ____    ____    __  __
               /\  _`\ /\  _`\ /\ \/\ \
               \ \,\L\_\ \,\L\_\ \ \_\ \
                \/_\__ \\/_\__ \\ \  _  \
                  /\ \L\ \/\ \L\ \ \ \ \ \
                  \ `\____\ `\____\ \_\ \_\
                   \/_____/\/_____/\/_/\/_/
  ______                                 __
 /\__  _\                               /\ \__  __
 \/_/\ \/     ___     ___     __   _____\ \ ,_\/\_\    ___     ___
    \ \ \   /' _ `\  /'___\ /'__`\/\ '__`\ \ \/\/\ \  / __`\ /' _ `\
     \_\ \__/\ \/\ \/\ \__//\  __/\ \ \L\ \ \ \_\ \ \/\ \L\ \/\ \/\ \
     /\_____\ \_\ \_\ \____\ \____\\ \ ,__/\ \__\\ \_\ \____/\ \_\ \_\
     \/_____/\/_/\/_/\/____/\/____/ \ \ \/  \/__/ \/_/\/___/  \/_/\/_/
                                     \ \_\
                                      \/_/
It's a week the first level down. Six months the second level down, and... the third level...

        Welcome to SSH Inception. The goal is to answer all questions by exploring
    the local network, the subnet OCTET.0.0.0/27. You are currently at the Starting Line.

    For every host you login to you will be greeted with instructions. Each host
    will give you a list of useful commands to solve each challenge. Use man
    pages to help find useful options for commands.

    Every stop has a file named 'secret' with a code inside. Submit these codes on
    EDURange to verify your progress.


Go a level deeper. You will find the next host at OCTET.0.0.7.
The trick is that the ssh port has been changed to 123.
Your ssh username and password for the next stop are the same that got you here.

Good luck!

Helpful commands: ssh, help, man
EOF
