#!/bin/bash

set -eoux pipefail

cat << \EOF >/etc/motd
 ███████╗██╗██████╗ ███████╗████████╗    ███████╗████████╗ ██████╗ ██████╗
 ██╔════╝██║██╔══██╗██╔════╝╚══██╔══╝    ██╔════╝╚══██╔══╝██╔═══██╗██╔══██╗
 █████╗  ██║██████╔╝███████╗   ██║       ███████╗   ██║   ██║   ██║██████╔╝
 ██╔══╝  ██║██╔══██╗╚════██║   ██║       ╚════██║   ██║   ██║   ██║██╔═══╝
 ██║     ██║██║  ██║███████║   ██║       ███████║   ██║   ╚██████╔╝██║
 ╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝   ╚═╝       ╚══════╝   ╚═╝    ╚═════╝ ╚═╝

"I'll tell you a riddle. You're waiting for a train, a train that will take
you far away. You know where you hope this train will take you, but you don't
know for sure."

You found it. Well done. The next dream machine lies just a few addresses
higher on your subnet. Use nmap to find the next closest machine.

Helpful commands: ifconfig, nmap, ssh
EOF
