#!/bin/bash

awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd > /usr/local/src/user_names.txt

while read line; do
	echo -e "95541890\\n95541890" | passwd $line
done</usr/local/src/user_names.txt
