#!/bin/bash
set -euxo pipefail
login=$1
satans_palace_password=$2
echo "You found me. Good job. The next challenge will not be so easy. You will find Satans Palace on the host with a certain open port. The most evil open port. SSH to that port with the password '${satans_palace_password}'. The final treasure awaits... maybe you can steal it, without ever going in..." | base64 > /home/$login/betcha_cant_read_me
chown $login:$login /home/$login/betcha_cant_read_me
chmod 440 /home/$login/betcha_cant_read_me
