#!/bin/bash
set -euxo pipefail

/home/ubuntu/setup_home "jack" "asdf1234" "1234asdf"

mkdir /usr/special/
mkdir /usr/special/secrets
cp /home/ubuntu/final-mission/U348bdks8cowFJS8dJF3hHDFj.jpg /usr/special/secrets/
cp /home/ubuntu/final-mission/.donthackme /usr/special/secrets/
chmod 666 /usr/special/secrets/U348bdks8cowFJS8dJF3hHDFj.jpg
chmod 666 /usr/special/secrets/.donthackme
#rm -rf /home/ubuntu/install
#rm -rf /home/ubuntu/setup_home
#rm -rf /home/ubuntu/stuff
#rm -rf /home/ubuntu/toLearn
#rm -rf /home/ubuntu/images
rm -rf /home/ubuntu/final-mission
