#!/usr/bin/env bash

message=$(cat << "EOF"
    #############  GETTING STARTED #############
    Welcome to the Getting Started EDURange scenario!
    Follow the instructions in the CodeLabs and answer the questions on EDURange.
    ############################################
EOF
)

  cd /home/jack
  echo "$message" > message
  chmod 404 message
  echo 'cat message' >> .bashrc

