"""empty message

Revision ID: 701b8b4e7cce
Revises: 4da2137aa885
Create Date: 2020-02-11 14:49:29.445336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701b8b4e7cce'
down_revision = '4da2137aa885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
