#!/bin/bash

set -eoux pipefail

cat << \EOF >/etc/motd
***********************************************************************************
***********************************************************************************
 ______  _______    _   _____    _    _______        ______   ______ _______    ______            _    _______
(_____ \(_______)  | | (_____)  | |  (_______)  /\  |  ___ \ / _____|_______)  (____  \   /\     | |  (_______)
 _____) )_____      \ \   _      \ \  _        /  \ | |   | | /      _____      ____)  ) /  \     \ \  _____
(_____ (|  ___)      \ \ | |      \ \| |      / /\ \| |   | | |     |  ___)    |  __  ( / /\ \     \ \|  ___)
      | | |_____ _____) )| |_ _____) ) |_____| |__| | |   | | \_____| |_____   | |__)  ) |__| |_____) ) |_____
      |_|_______|______(_____|______/ \______)______|_|   |_|\______)_______)  |______/|______(______/|_______)

You found your way into the resistance base! When you get there, you find they already know you.
This isn't the first time you've done this. Without time to fill in your back story (your help
is needed immediately), you get informed on a plan to carry out a massive coordinated attack
on the evil corporate headquarters. The resistance needs to know some valuable information about
three different servers, but they can't risk being detected. They ask you to use your spy skills
to do some stealthy reconnaissance. Are you ready for some serious spy business?

Nmap has a variety of methods to scan ports. The most basic (and default for non-root users)
 port scan simply attempts to connect() to each port, which attempts to perform the 3-way
handshake and make a connection. A slightly more sophisticated scan is the TCP SYN scan,
[ nmap -Ss host ]
This scan sends an initial TCP packet with the SYN flag, but then does not respond to the
hosts SYN/AWK packet. While slightly less obvious than the TCP connect() scan, it doesn't
take much to figure out when this kind of scan is occurring.

To have a better chance of scanning undetected, it is better to use FIN, Null and
Xmas Tree Scans.
                                 |L
                                ,' `
                               /.o `,
                               `, |-`,
                              -',    '
                             `,'_)   '\
                             ,'    `-`,
                            _`o,-   (_)/
                           '_ '    o  `-,
                           /   ,-L   `-'
                          _`-`_     ,  `'.
                         ;.  (,'  `| `.-. \
                         ,``_'    (_)  o `'
                        ,` '_  ,|\   o   _ \
                       /..-(_)' |','..-`(_)-`
                                |  |
                              --'  `--
The hosts in the range 10.0.233.34 - 38 are your targets. You need to scan them while remaining
undetected. Not every scan type will work on each host. Figuring which hosts block which
scans will help the resistance gain the valuable information they need.

Check out the man page for Nmap or this helpful link to learn more about stealth scans:
https://nmap.org/bennieston-tutorial/

After you've helped the Resistance gain valuable intel on their targets, you're ready for the
final struggle. The information you've obtained indicates that the corporate authority has
kept secret its terraforming technology. They have a secret reactor which could transform the Martian
atmosphere into breathable air. The people of mars would no longer rely on the Mars corporation.
You must find the reactor and turn it on.

Find the Reactor Control Room -- the IP ends in .5, but the entrance is hidden among many decoys...

***********************************************************************************
***********************************************************************************
EOF
