#!/bin/bash
echo "* * * * * /home/ubuntu/check_reactors" > /home/ubuntu/crontab_entry
crontab /home/ubuntu/crontab_entry

while read line;
  do
    #make reactor and .secret directories
    cd /home/$line
    cat /etc/motd > instructions.txt
    mkdir reactor
    mkdir reactor/.secret
    cd reactor/.secret
    cp /home/ubuntu/control_script .
    echo 5 > countdown
    echo $line > user
    echo "OFF" > reactor_state
    chown $line reactor_state
    444 reactor_state
    722 countdown
    744 user
    700 control_script
done</usr/local/src/user_names.txt

echo "echo 5 > ~/reactor/.secret/countdown;if [ -e ~/BOOM ]; then rm -f ~/BOOM;fi" >> /etc/bash.bashrc
echo "alias chmod='chmod;echo It looks like someone moved chmod... I wonder where it is...'" >> /etc/bash.bashrc

mkdir /look-in-here
mv /bin/chmod /look-in-here/chmod
