#!/bin/bash
set -euxo pipefail
strace which start 2>&1 | tail -n +2 > strace-identify || :
gcc -o mystery mystery.c
rm mystery.c
gcc -o cat trojaned_cat.c
chmod 4771 cat
mv cat /usr/local/bin
rm trojaned_cat.c
%{for player in players ~}
f=/home/${player.login}
cp copy.c $f
cp empty.c $f
cp hello.c $f
cp strace-identify $f
cp tiger.txt $f
cp mystery $f
cp script.sh $f
chown ${player.login}:${player.login} $f/*
chmod 644 $f/copy.c $f/empty.c $f/hello.c $f/strace-identify $f/tiger.txt
chmod 755 $f/mystery $f/script.sh
chmod go-rx $f
%{ endfor ~}

if [ ! -d "/tmp/data" ]; then
  mkdir /tmp/data
fi
chmod 711 /tmp/data
touch /tmp/data/filenames
chmod 774 /tmp/data/filenames

chmod 4751 /usr/bin/strace
