#!/bin/bash

set -eoux pipefail

/bin/cat << \EOF >/etc/motd
 _____ ___________  ___  _____  _____
/  ___|_   _| ___ \/ _ \/  __ \|  ___|
\ `--.  | | | |_/ / /_\ \ /  \/| |__
 `--. \ | | |    /|  _  | |    |  __|
/\__/ / | | | |\ \| | | | \__/\| |___
\____/  \_/ \_| \_\_| |_/\____/\____/

Learn about linux system calls and how to perform dynamic analysis of a binary using strace
EOF

echo '/bin/cat /etc/motd' >> /etc/bash.bashrc
