#!/bin/bash

set -eoux pipefail

cat << \EOF >/etc/motd
****************************************************************
__          __  _                            _______    
\ \        / / | |                          |__   __|   
 \ \  /\  / /__| | ___ ___  _ __ ___   ___     | | ___  
  \ \/  \/ / _ \ |/ __/ _ \| '_ ` _ \ / _ \    | |/ _ \ 
   \  /\  /  __/ |  \_| _  | | | | | |  __/    | |  _ |
    \/  \/ \___|_|\___\___/|_| |_| |_|\___|    |_|\___/

 ______ _ _       __          __                    _           
|  ____(_) |      \ \        / /                   | |          
| |__   _| | ___   \ \  /\  / / __ __ _ _ __   __ _| | ___ _ __ 
|  __| | | |/ _ \   \ \/  \/ / '__/ _` | '_ \ / _` | |/ _ \ '__|
| |    | | |  __/    \  /\  /| | | (_| | | | | (_| | |  __/ |   
|_|    |_|_|\___|     \/  \/ |_|  \__,_|_| |_|\__, |_|\___|_|   
                                               __/ |            
                                              |___/           

In this exercise, you will work through a series of Linux
command-line challenges for managing files and file permissions.

Start by viewing the contents of the instructions.txt file with
the following command:
cat instructions.txt

****************************************************************
EOF

echo 'cat /etc/motd' >> /etc/bash.bashrc
