#!/bin/bash
set -eoux pipefail

mv /home/ubuntu/file_wrangler/python/perflag /usr/bin/perflag
mv /home/ubuntu/file_wrangler/python/manflag /usr/bin/manflag
chmod u+x,g+x,o-rwx /usr/bin/perflag
chmod u+x,g+x,o-rwx /usr/bin/manflag

%{ for player in players ~}
/home/ubuntu/file_wrangler/setup_player ${player.login} ${player.variables.manipulate} ${player.variables.permissions}
%{ endfor ~}
rm -r /home/ubuntu/file_wrangler
