#!/bin/bash
set -eoux pipefail

player=$1
man_flag=$2
perm_flag=$3
studentDIR=/home/$player

# Copy the file hierarchy to each home directory
cp -R /home/ubuntu/file_wrangler/files/* $studentDIR/

# Use EDURange variables for flags
echo "SECRET FLAG: $man_flag \n CONGRATULATIONS! You're a file-wrangling expert!" > $studentDIR/codes/manipulate.txt
echo "SECRET FLAG: $perm_flag \n CONGRATULATIONS! You're a file-wrangling expert!" > $studentDIR/codes/permissions.txt

# Set file permissions
chmod 600 $studentDIR/codes/manipulate.txt
chmod 600 $studentDIR/codes/permissions.txt

# Set file ownership
chown $player -R $studentDIR/manipulate/
chown $player -R $studentDIR/permissions/
#chown $player /$studentDIR/manipulate/file1.txt
#chown $player /$studentDIR/manipulate/file2.txt
#chown $player /$studentDIR/permissions/perm1.txt
#chown $player /$studentDIR/permissions/perm2.txt

# Set python to run as root
#chown root:root $studentDIR/manipulate/manflag.pyc
#chmod 4775 $studentDIR/manipulate/manflag.pyc
echo "$player ALL=(ALL) NOPASSWD: /usr/bin/perflag" >> /etc/sudoers
echo "$player ALL=(ALL) NOPASSWD: /usr/bin/manflag" >> /etc/sudoers
#echo "$player ALL = (root) NOPASSWD: $studentDIR/permissions/perflag.pyc" >> /etc/sudoers
